### ISSUE TITLE
https://pypi.org/simple/entropy/ package not found

### ISSUE THREAD

**Issue by dfirnewbie** [x0rz/phishing_catcher#53]
When I installing phishing_catcher, I got the following error:

`Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/entropy/`

I tried finding on Google if there's any similar packages, but there are too many (results: [https://pypi.org/search/?q=entropy](https://pypi.org/search/?q=entropy)) and I'm not too sure which package to use.

May I know what should this package be replaced with?

**Comment by dfirnewbie** [comment]
Issue resolved...

I referred to the dependencies page ([https://github.com/x0rz/phishing_catcher/network/dependencies](https://github.com/x0rz/phishing_catcher/network/dependencies)) and found the `entropy` package to install, and removed the line from requirements.txt after successfully installing `entropy`.

**Comment by morriscode** [comment]
I did the same thing as above... however after installing entropy it just barfs.

`certificate_update: 0cert [00:00, ?cert/s][INFO:root] 2020-02-27 17:57:48,119 - Connection established to CertStream! Listening for events...
certificate_update: 1cert [00:01,  1.25s/cert][ERROR:websocket] 2020-02-27 17:57:49,141 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb21597e278>>: module 'entropy' has no attribute 'shannon_entropy'
[ERROR:websocket] 2020-02-27 17:57:49,189 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb21597e278>>: module 'entropy' has no attribute 'shannon_entropy'
[ERROR:websocket] 2020-02-27 17:57:49,213 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb21597e278>>: module 'entropy' has no attribute 'shannon_entropy'
certificate_update: 4cert [00:01,  1.13cert/s][ERROR:websocket] 2020-02-27 17:57:49,228 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb21597e278>>: module 'entropy' has no attribute 'shannon_entropy'
[ERROR:websocket] 2020-02-27 17:57:49,250 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb21597e278>>: module 'entropy' has no attribute 'shannon_entropy'
[ERROR:websocket] 2020-02-27 17:57:49,290 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb21597e278>>: module 'entropy' has no attribute 'shannon_entropy'
[ERROR:websocket] 2020-02-27 17:57:49,312 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb21597e278>>: module 'entropy' has no attribute 'shannon_entropy'
`

**Comment by gthubs** [comment]
Hello. I was able to solve the error `module 'entropy' has no attribute 'shannon_entropy' `
As I understood the reason in the wrong entropy module (like here github.com/raphaelvallat/entropy/releases).

I hardly found the entropy-0.10.tar.gz, here is the link files.pythonhosted.org/packages/8c/34/f1d90497254a2b7ce23787773db4a0a1928405bf96108c20070c8029aaa8/entropy-0.10.tar.gz
I hope it’s safe, but if there are specialists, check the code just in case. And if anyone can save the archive in a reliable hosting plese do it.

So the complete instruction for beginners (like me) for Debian 10 (debian-live-10.3.0-amd64-xfce)
1. `sudo apt-get update && sudo apt-get -y upgrade`
2. `sudo apt-get install python3-pip`
3. Download entropy-0.10.tar.gz (link above), unzip, go to the folder, open terminal and command `sudo pip3 install -r requirements.txt` and after `python3 setup.py develop`
4. Download phishing_catcher-master.zip, unzip, go to folder, find requirements.txt and delete line entropy==0.10 (because there is 404 error), save
5. Open terminal, command `sudo pip3 install -r requirements.txt` and after `python3 catch_phishing.py` for run script

**Comment by vicky14rockz** [comment]
still having issue.. .mr. x0rz can you sort this?

**Comment by x0rz** [comment]
This should be fixed now (https://github.com/x0rz/phishing_catcher/commit/267a597205fb5dec0f70bac3298e09927463fe9d)
